// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yljqietzgtjmwvgxiuot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsanFpZXR6Z3RqbXd2Z3hpdW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjU5NjYsImV4cCI6MjA2OTcwMTk2Nn0.XyETUUc9tOXsgyG2hzJQELZoJd1RS32ERRzUyB0nmzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});